"""Deterministic request generator for Understudy load generation.

Conforms to ADR-015: load is generated deterministically given an integer seed.
"""

import random
from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True)
class RequestSpec:
    """Specification for a single HTTP request in the load generation sequence."""

    method: str
    path: str
    headers: dict[str, str] = field(default_factory=dict)
    json_body: dict[str, Any] | None = None


class SeededRequestGenerator:
    """Generates a deterministic sequence of HTTP requests using a seeded pseudo-random engine."""

    def __init__(self, seed: int = 42, auth_token: str = "valid-token") -> None:
        self.seed = seed
        self.auth_token = auth_token
        self._rng = random.Random(seed)

    def generate_spec(self, sequence_id: int) -> RequestSpec:
        """Generate a single deterministic RequestSpec.

        Mix: 80% GET /api/items, 20% POST /api/items with catalogue creation payload.
        """
        auth_header = f"Bearer {self.auth_token}"
        headers = {
            "Authorization": auth_header,
            "User-Agent": "understudy-loadgen/1.0",
        }

        # 80% read / catalogue retrieval, 20% item creation
        if self._rng.random() < 0.8:
            return RequestSpec(
                method="GET",
                path="/api/items",
                headers=headers,
                json_body=None,
            )

        item_id = f"item-{self.seed}-{sequence_id}"
        json_body = {
            "name": f"Loadgen Item {sequence_id}",
            "description": f"Seeded item generated by understudy loadgen (seed={self.seed})",
            "details": [
                {"key": "generator", "value": "understudy-loadgen"},
                {"key": "seed", "value": str(self.seed)},
                {"key": "seq", "value": str(sequence_id)},
                {"key": "item_id", "value": item_id},
            ],
        }
        return RequestSpec(
            method="POST",
            path="/api/items",
            headers=headers,
            json_body=json_body,
        )

    def generate_batch(self, count: int) -> list[RequestSpec]:
        """Generate a deterministic batch of `count` RequestSpecs."""
        return [self.generate_spec(i) for i in range(count)]
