"""Candidate-generation prompt builder, output schemas, and response parser.

Implements build-plan step B3.1 over the closed action enum:
- Inputs: IncidentContext serialized, closed action enum, dependency graph,
  available deploy refs, and optional playbook match.
- Output: Strict JSON matching PlannerPromptResponse with N plans, each specifying
  action, params, declared_blast_set, inverse, and rationale.
"""

import json
import re
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, ValidationError

from understudy.common.errors import PlannerError
from understudy.contracts.enums import ActionType
from understudy.contracts.incident import (
    Alert,
    DeployRef,
    ErrorSignature,
    IncidentContext,
    MetricWindow,
)
from understudy.contracts.plan import (
    ActionParams,
    RemediationPlan,
    ResourceRef,
)


class PromptInversePlan(BaseModel):
    """Inverse plan representation produced by or supplied to the prompt."""

    model_config = ConfigDict(frozen=True)

    action: ActionType = Field(
        ...,
        description="Action type for the inverse plan.",
    )
    params: ActionParams = Field(
        ...,
        description="Parameters for the inverse plan.",
    )
    declared_blast_set: list[str] = Field(
        default_factory=list,
        description="Services expected to be affected by applying this inverse plan.",
    )
    rationale: str = Field(
        ...,
        description="Technical rationale explaining how this inverse restores prior state.",
    )


class PromptCandidatePlan(BaseModel):
    """A single candidate remediation plan generated by the LLM."""

    model_config = ConfigDict(frozen=True)

    action: ActionType = Field(
        ...,
        description="Action from the closed ActionType enum.",
    )
    params: ActionParams = Field(
        ...,
        description="Parameters required for this specific action type.",
    )
    declared_blast_set: list[str] = Field(
        default_factory=list,
        description="List of service names from the dependency graph expected to be affected.",
    )
    inverse: PromptInversePlan | None = Field(
        default=None,
        description=(
            "Inverse plan reversing this action. Optional; if omitted, Understudy "
            "synthesizes the inverse deterministically."
        ),
    )
    rationale: str = Field(
        ...,
        description="Concise technical reasoning justifying this remediation candidate.",
    )


class PlannerPromptResponse(BaseModel):
    """Top-level JSON payload emitted by the candidate-generation LLM."""

    model_config = ConfigDict(frozen=True)

    plans: list[PromptCandidatePlan] = Field(
        ...,
        description="List of candidate remediation plans.",
    )


def prompt_candidate_to_remediation_plan(
    candidate: PromptCandidatePlan,
    candidate_index: int,
    plan_id: str | None = None,
    origin: Literal["planner", "playbook", "shadow"] = "planner",
    playbook_id: str | None = None,
    default_namespace: str = "ust-twin",
) -> RemediationPlan:
    """Convert a PromptCandidatePlan into a frozen RemediationPlan contract."""
    assigned_plan_id = plan_id or f"plan_cand_{candidate_index}"

    inverse_plan: RemediationPlan | None = None
    if candidate.inverse is not None and candidate.action != ActionType.NO_ACTION:
        inverse_resources: list[ResourceRef] = []
        if candidate.inverse.params.workload:
            inv_kind: Literal["Deployment", "ConfigMap"] = (
                "ConfigMap"
                if candidate.inverse.action == ActionType.REVERT_CONFIG
                else "Deployment"
            )
            inverse_resources.append(
                ResourceRef(
                    namespace=default_namespace,
                    kind=inv_kind,
                    name=candidate.inverse.params.workload,
                )
            )
        inverse_plan = RemediationPlan(
            plan_id=f"{assigned_plan_id}_inv",
            candidate_index=candidate_index,
            action=candidate.inverse.action,
            params=candidate.inverse.params,
            target_resources=inverse_resources,
            declared_blast_set=list(candidate.inverse.declared_blast_set),
            inverse=None,
            rationale=candidate.inverse.rationale,
            origin=origin,
        )

    target_resources: list[ResourceRef] = []
    if candidate.params.workload and candidate.action != ActionType.NO_ACTION:
        kind: Literal["Deployment", "ConfigMap"] = (
            "ConfigMap" if candidate.action == ActionType.REVERT_CONFIG else "Deployment"
        )
        target_resources.append(
            ResourceRef(
                namespace=default_namespace,
                kind=kind,
                name=candidate.params.workload,
            )
        )

    return RemediationPlan(
        plan_id=assigned_plan_id,
        candidate_index=candidate_index,
        action=candidate.action,
        params=candidate.params,
        target_resources=target_resources,
        declared_blast_set=list(candidate.declared_blast_set),
        inverse=inverse_plan,
        rationale=candidate.rationale,
        origin=origin,
        playbook_id=playbook_id,
    )


def format_alert(alert: Alert) -> str:
    """Format an incident alert into human-readable text."""
    lines = [
        f"Alert ID: {alert.alert_id}",
        f"Source: {alert.source}",
        f"Title: {alert.title}",
        f"Primary Service: {alert.service}",
        f"Severity: {alert.severity}",
        f"Fired At: {alert.fired_at.isoformat()}",
    ]
    if alert.raw:
        lines.append(f"Raw Details: {json.dumps(alert.raw, sort_keys=True)}")
    return "\n".join(lines)


def format_signatures(signatures: list[ErrorSignature]) -> str:
    """Format aggregated error signatures from Loki logs."""
    if not signatures:
        return "None observed."
    lines: list[str] = []
    for idx, sig in enumerate(signatures, start=1):
        lines.append(
            f"{idx}. [{sig.service}] count={sig.count} fingerprint={sig.fingerprint}\n"
            f"   message: {sig.message}\n"
            f"   first_seen: {sig.first_seen.isoformat()} last_seen: {sig.last_seen.isoformat()}"
        )
    return "\n".join(lines)


def format_metrics(metrics: MetricWindow) -> str:
    """Format metrics window telemetry from Prometheus."""
    p99 = f"{metrics.p99_latency_ms:.1f} ms" if metrics.p99_latency_ms is not None else "N/A"
    err = f"{metrics.error_rate * 100:.2f}%" if metrics.error_rate is not None else "N/A"
    lines = [
        f"Target Service: {metrics.service}",
        f"Window: {metrics.start_time.isoformat()} to {metrics.end_time.isoformat()}",
        f"Total Requests: {metrics.request_count}",
        f"p99 Latency: {p99}",
        f"Error Rate: {err}",
    ]
    if metrics.series:
        lines.append("Series:")
        for s in metrics.series:
            labels_str = ",".join(f"{k}={v}" for k, v in sorted(s.labels.items()))
            labels_part = f"{{{labels_str}}}" if labels_str else ""
            val = f"{s.points[-1].value:.2f}" if s.points else "N/A"
            lines.append(f"  - {s.metric_name}{labels_part}: latest_value={val}")
    return "\n".join(lines)


def format_deploys(deploys: list[DeployRef]) -> str:
    """Format recent GitHub deploy history and image digests."""
    if not deploys:
        return "No recent deployments recorded."
    lines: list[str] = []
    for idx, d in enumerate(deploys, start=1):
        digests = ", ".join(f"{svc}={digest}" for svc, digest in sorted(d.image_digests.items()))
        lines.append(
            f"{idx}. commit: {d.commit_sha} deployed_at: {d.deployed_at.isoformat()} "
            f"pr: {d.pr_number or 'N/A'} contains_migration: {d.contains_migration}\n"
            f"   images: {digests or 'none'}"
        )
    return "\n".join(lines)


def format_dependency_graph(context: IncidentContext) -> str:
    """Format dependency graph topology (services and caller -> callee edges)."""
    graph = context.dependency_graph
    nodes_str = ", ".join(sorted(graph.nodes)) if graph.nodes else "None"
    lines = [f"Services (nodes): {nodes_str}"]
    if graph.edges:
        lines.append("Dependencies (edges, caller -> callee):")
        for edge in sorted(graph.edges, key=lambda e: (e.source, e.target)):
            lines.append(f"  - {edge.source} -> {edge.target}")
    else:
        lines.append("Dependencies (edges): None declared")
    return "\n".join(lines)


def format_playbook_candidate(playbook: RemediationPlan | None) -> str:
    """Format retrieved playbook match if available."""
    if playbook is None:
        return "None matched."
    params_dict = playbook.params.model_dump(exclude_none=True)
    return (
        f"Playbook ID: {playbook.playbook_id or 'unknown'}\n"
        f"Recommended Action: {playbook.action.value}\n"
        f"Parameters: {json.dumps(params_dict, sort_keys=True)}\n"
        f"Declared Blast Set: {', '.join(playbook.declared_blast_set) or 'none'}\n"
        f"Rationale: {playbook.rationale}"
    )


def format_incident_context(
    context: IncidentContext,
    playbook_candidate: RemediationPlan | None = None,
) -> str:
    """Serialize full IncidentContext into structured textual prompt sections."""
    inferred_fc = (
        context.inferred_failure_class.value
        if context.inferred_failure_class is not None
        else "Unknown"
    )
    sections = [
        (
            f"=== INCIDENT IDENTIFIER ===\n"
            f"Incident ID: {context.incident_id}\n"
            f"Gathered At: {context.gathered_at.isoformat()}"
        ),
        f"=== INFERRED FAILURE CLASS ===\n{inferred_fc}",
        f"=== ACTIVE ALERT ===\n{format_alert(context.alert)}",
        f"=== ERROR SIGNATURES (LOGS) ===\n{format_signatures(context.signatures)}",
        f"=== METRICS TELEMETRY ===\n{format_metrics(context.metrics_window)}",
        f"=== RECENT DEPLOYMENTS (GITHUB) ===\n{format_deploys(context.recent_deploys)}",
        f"=== DEPENDENCY GRAPH ===\n{format_dependency_graph(context)}",
        f"=== PLAYBOOK MATCH CANDIDATE ===\n{format_playbook_candidate(playbook_candidate)}",
    ]
    return "\n\n".join(sections)


def get_planner_output_schema() -> dict[str, Any]:
    """Return the JSON schema for PlannerPromptResponse."""
    return PlannerPromptResponse.model_json_schema()


def build_system_prompt() -> str:
    """Build the system prompt instructing the LLM on candidate plan generation."""
    schema_json = json.dumps(get_planner_output_schema(), indent=2)

    return f"""You are the Autonomous Remediation Planner for Understudy.
Your task is to analyze incident diagnostics and generate candidate remediation plans.

CLOSED ACTION ENUMERATION:
You must ONLY select actions from the following closed enum. Unlisted actions are forbidden:
1. "rollback_deploy":
   - Description: Roll back a service Deployment to a prior commit SHA and image digest.
   - Parameters: workload (service name), target_commit (the Git commit SHA to roll back to).
   - Rules: target_commit MUST be chosen from recent deployments. Do NOT roll back across
     a commit where contains_migration is true.
   - Inverse: Roll forward to the current pre-incident commit.
2. "restart_workload":
   - Description: Trigger a rolling restart of all pods for the specified workload Deployment.
   - Parameters: workload (service name).
   - Inverse: Another rolling restart, or null if idempotent.
3. "scale_workload":
   - Description: Scale a workload Deployment by a replica delta.
   - Parameters: workload (service name), replica_delta (integer delta, e.g. +1, +2, -1).
     Cannot scale to 0.
   - Inverse: Scale back by the opposite replica delta (-replica_delta).
4. "disable_flag":
   - Description: Disable an active feature flag in service configuration.
   - Parameters: workload (service name), flag_name (name of the feature flag).
   - Inverse: Re-enable the feature flag.
5. "revert_config":
   - Description: Revert a configuration key in a ConfigMap back to its prior value.
   - Parameters: workload (service name), config_key (key name), config_value (prior value).
   - Inverse: Re-apply the modified configuration key and value.
6. "no_action":
   - Description: Explicitly take no action when intervention is dangerous or unnecessary.
   - Parameters: workload (primary alert service).
   - Inverse: null.

SAFETY AND FORMAL INVARIANT REQUIREMENTS:
- Target Workload: Must be an existing service named in the Dependency Graph or Alert.
- Declared Blast Set: You must declare all services expected to experience metric or traffic
  impact. This MUST be a subset of services present in the dependency graph topology.
- Reversibility: Every plan except "no_action" is reversible. Understudy synthesizes
  all inverse plans deterministically per ADR-016. For "no_action", the inverse field is null.
- Diversity: When asked for N candidates, generate diverse, distinct hypotheses (e.g. rollback
  vs scale vs restart vs config revert) rather than minor variations of the same action.
- Playbook Match: If a playbook match candidate is provided, evaluate whether it fits the
  observed error signatures and incorporate or adapt it as one candidate if viable.

OUTPUT FORMAT:
You must respond with valid JSON conforming exactly to the following JSON schema:
{schema_json}

CRITICAL RULES:
- Output valid JSON ONLY.
- Do NOT wrap your output in conversational text, preamble, or postscript.
- Do NOT propose arbitrary bash commands, scripts, or manual operator instructions.
- Ensure all property names match the schema exactly.
"""


def build_user_prompt(
    context: IncidentContext,
    count: int = 3,
    playbook_candidate: RemediationPlan | None = None,
) -> str:
    """Build the user prompt containing serialized incident diagnostics and plan count."""
    serialized_context = format_incident_context(context, playbook_candidate=playbook_candidate)

    return f"""The following incident has been detected in the production environment.

{serialized_context}

INSTRUCTION:
Generate exactly {count} distinct, viable, and diverse candidate remediation plans.
Each candidate must belong to the closed action enum. Inverses are synthesized deterministically.
Output the response as a JSON object matching the required schema with the "plans" array.
"""


def render_candidate_generation_prompt(
    context: IncidentContext,
    count: int = 3,
    playbook_candidate: RemediationPlan | None = None,
) -> list[dict[str, str]]:
    """Render full OpenAI/OpenRouter chat messages structure for candidate generation."""
    return [
        {"role": "system", "content": build_system_prompt()},
        {
            "role": "user",
            "content": build_user_prompt(
                context, count=count, playbook_candidate=playbook_candidate
            ),
        },
    ]


def parse_raw_planner_json(raw_text: str) -> PlannerPromptResponse:
    """Parse and validate raw JSON response text from the planner LLM.

    Handles optional markdown code fences and raises PlannerError on invalid JSON
    or schema violations.
    """
    text = raw_text.strip()

    # Strip optional markdown code fences: ```json ... ``` or ``` ... ```
    match = re.search(r"```(?:json)?\s*([\s\S]*?)\s*```", text, re.IGNORECASE)
    if match:
        text = match.group(1).strip()

    try:
        parsed = json.loads(text)
    except json.JSONDecodeError as exc:
        raise PlannerError(
            f"Failed to decode planner response as JSON: {exc.msg} at line {exc.lineno}",
            details={"raw_text": raw_text[:500]},
        ) from exc

    try:
        return PlannerPromptResponse.model_validate(parsed)
    except ValidationError as exc:
        raise PlannerError(
            f"Planner response violates output schema: {exc}",
            details={"errors": exc.errors()},
        ) from exc
