"""Tournament package: candidate observation, scoring, and arbitration."""

from understudy.tournament.api import (
    BlastTracker,
    CandidateScorer,
    EnvironmentProbe,
    LLMJudge,
    Tournament,
)
from understudy.tournament.arbiter import (
    ArbiterConfig,
    RehearsalTournament,
    TournamentArbiter,
    arbitrate,
)
from understudy.tournament.blast import (
    BlastConfig,
    BlastCoordinator,
    BlastEvaluation,
    EnvironmentBaseline,
    compute_affected_services,
    compute_blast_radius,
    compute_downstream_error_delta,
    evaluate_blast,
)
from understudy.tournament.fakes import (
    FakeBlastTracker,
    FakeEnvironmentProbe,
    FakeLLMJudge,
    FakeTournament,
)
from understudy.tournament.judge import (
    AdvisoryLLMJudge,
    JudgeAPIError,
    JudgeConfig,
    JudgeConfigError,
    JudgeError,
    JudgeEvaluation,
    JudgeParseError,
    JudgeTimeoutError,
    build_judge_system_prompt,
    build_judge_user_prompt,
    compute_judge_agreement,
    parse_judge_response,
    serialize_evidence_for_judge,
)
from understudy.tournament.probe import (
    ProbeConfig,
    ProbeResult,
    ProbeSampler,
    detect_recovery,
)
from understudy.tournament.scorer import (
    DeterministicCandidateScorer,
    ScoringConfig,
    check_disqualification,
    compute_blast_subscore,
    compute_downstream_subscore,
    compute_recovery_subscore,
    compute_violations_subscore,
    load_scoring_config,
    score_candidate,
    score_candidates,
)

__all__ = [
    "AdvisoryLLMJudge",
    "ArbiterConfig",
    "BlastConfig",
    "BlastCoordinator",
    "BlastEvaluation",
    "BlastTracker",
    "CandidateScorer",
    "DeterministicCandidateScorer",
    "EnvironmentBaseline",
    "EnvironmentProbe",
    "FakeBlastTracker",
    "FakeEnvironmentProbe",
    "FakeLLMJudge",
    "FakeTournament",
    "JudgeAPIError",
    "JudgeConfig",
    "JudgeConfigError",
    "JudgeError",
    "JudgeEvaluation",
    "JudgeParseError",
    "JudgeTimeoutError",
    "LLMJudge",
    "ProbeConfig",
    "ProbeResult",
    "ProbeSampler",
    "RehearsalTournament",
    "ScoringConfig",
    "Tournament",
    "TournamentArbiter",
    "arbitrate",
    "build_judge_system_prompt",
    "build_judge_user_prompt",
    "check_disqualification",
    "compute_affected_services",
    "compute_blast_radius",
    "compute_blast_subscore",
    "compute_downstream_error_delta",
    "compute_downstream_subscore",
    "compute_judge_agreement",
    "compute_recovery_subscore",
    "compute_violations_subscore",
    "detect_recovery",
    "evaluate_blast",
    "load_scoring_config",
    "parse_judge_response",
    "score_candidate",
    "score_candidates",
    "serialize_evidence_for_judge",
]
